version: 2

seeds:
  - name: employees
    description: "Seed data for employees"
    columns:
      - name: employee_id
        description: "Unique identifier for each employee"
        tests:
          - not_null
          - unique
      - name: email
        description: "Email address of the employee"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Identifier for the customer associated with the employee"
        tests:
          - not_null